### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/morphology-db#1]
- Data normalization
  - [x] Fix homoglyph (cf. https://github.com/UniversalDependencies/UD_Russian-Taiga/issues/4)
  - [x] Force lower case (except proper noun or foreign word)
  - [x] Deal with incorrect lemma annotation (e.g. there exists lemma "легко" not just "легкий")
    - Use other resource (e.g. https://spacy.io/models/ru)
- Backend (API server)
  - /forms/:id
  - /forms/search
  - /lemmas/:id
  - /lemmas/search
  - /sentences/:id
  - [x] /search
    - [x] limit associated forms to return
  - [x] /fuzzy-search 
    - https://www.sqlite.org/spellfix1.html
    - [x] tweak edit distance cost table
    - [x] use also Form data, not only Lemma
  - [x] paginate response with too many forms (e.g. "быть")
- [ ] Frontend
- [ ] Deployment
  - [x] backend
    - [x] logging
    - [x] cloud run
    - [x] configuration
  - [ ] frontend
